/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import classeDados.Professor;

import java.util.ArrayList;
import javax.swing.JOptionPane;



import javax.swing.table.DefaultTableModel;
import persistencia.LerArquivo;


import persistencia.OrdenarMatricula;
import persistencia.OrdenarContratoNome;
import persistencia.OrdenarNome;
import persistencia.OrdenarContratoTitulacaoNome;
import persistencia.OrdenarDepartamentoNome;
import persistencia.OrdenarDepartamentoTitulacaoNome;
import persistencia.OrdenarTitulacaoNome;

/**
 *
 * @author leticiasilva
 */
public class Telaa extends javax.swing.JFrame {

    

    //private String arquivo1 = "./src/arquivo/DadosGerais.csv";
    //private String arquivo2 = "./src/arquivo/Professores.csv";
    private void imprimirNaGrid(ArrayList<Professor> listaDeProfessores) {

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1Tabela.getModel();
            model.setNumRows(0);
            
            //ArrayList<Professor> listaDeProfessores = new ArrayList<Professor>();;
            //listaDeProfessores = LerArquivo.lerCsv();

            for (int pos = 0; pos < listaDeProfessores.size(); pos++) {
                String[] saida = new String[5];
                Professor aux = listaDeProfessores.get(pos);
                saida[0] = aux.getMatricula();
                saida[1] = aux.getNome();
                saida[2] = aux.getDepartamento();
                saida[3] = aux.getTitulacao();
                saida[4] = aux.getContrato();
                //Incluir nova linha na Tabela
                model.addRow(saida);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }

    public Telaa() {
        initComponents();
    }
    
    

    /**
     * This method is called from within sthe constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOrdenarPorNome6 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Tabela = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButtonOrdenarDepartamentoTitulacaoNome = new javax.swing.JButton();
        jButtonOrdenarNome = new javax.swing.JButton();
        jButtonOrdenarTitulacaoNome = new javax.swing.JButton();
        jButtonOrdenarContratoNome = new javax.swing.JButton();
        jButtonOrdenarContratoTitulacaoNome = new javax.swing.JButton();
        jButtonOrdenarDepartamentoNome = new javax.swing.JButton();
        jButtonOrdenarMatricula = new javax.swing.JButton();

        jButtonOrdenarPorNome6.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarPorNome6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarPorNome6.setText("Ordenar por Nome");
        jButtonOrdenarPorNome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPorNome6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1Tabela.setAutoCreateRowSorter(true);
        jTable1Tabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Departamento", "Titulo", "Contrato"
            }
        ));
        jTable1Tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1Tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1Tabela);
        if (jTable1Tabela.getColumnModel().getColumnCount() > 0) {
            jTable1Tabela.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTable1Tabela.getColumnModel().getColumn(2).setPreferredWidth(12);
            jTable1Tabela.getColumnModel().getColumn(3).setPreferredWidth(12);
        }

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonOrdenarDepartamentoTitulacaoNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarDepartamentoTitulacaoNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarDepartamentoTitulacaoNome.setText("Departamento + Titulação + Nome");
        jButtonOrdenarDepartamentoTitulacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarDepartamentoTitulacaoNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarNome.setText("Ordenar por Nome");
        jButtonOrdenarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarTitulacaoNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarTitulacaoNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarTitulacaoNome.setText("Titulação + Nome");
        jButtonOrdenarTitulacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarTitulacaoNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarContratoNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarContratoNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarContratoNome.setText("Contrato + Nome");
        jButtonOrdenarContratoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarContratoNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarContratoTitulacaoNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarContratoTitulacaoNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarContratoTitulacaoNome.setText("Contrato + Titulação +Nome");
        jButtonOrdenarContratoTitulacaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarContratoTitulacaoNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarDepartamentoNome.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarDepartamentoNome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarDepartamentoNome.setText("Departamento + nome");
        jButtonOrdenarDepartamentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarDepartamentoNomeActionPerformed(evt);
            }
        });

        jButtonOrdenarMatricula.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOrdenarMatricula.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonOrdenarMatricula.setText("Ordenar por Matrícula");
        jButtonOrdenarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jButtonOrdenarContratoTitulacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarDepartamentoTitulacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarContratoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarTitulacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOrdenarDepartamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonOrdenarContratoNome, jButtonOrdenarContratoTitulacaoNome, jButtonOrdenarDepartamentoNome, jButtonOrdenarDepartamentoTitulacaoNome, jButtonOrdenarMatricula, jButtonOrdenarNome, jButtonOrdenarTitulacaoNome});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonOrdenarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarContratoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarTitulacaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarDepartamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarDepartamentoTitulacaoNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenarContratoTitulacaoNome)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, jButtonOrdenarContratoNome, jButtonOrdenarContratoTitulacaoNome, jButtonOrdenarDepartamentoNome, jButtonOrdenarDepartamentoTitulacaoNome, jButtonOrdenarMatricula, jButtonOrdenarNome, jButtonOrdenarTitulacaoNome});

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrdenarPorNome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPorNome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrdenarPorNome6ActionPerformed

    private void jButtonOrdenarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarMatriculaActionPerformed
        try {
            OrdenarMatricula objeto = new OrdenarMatricula();
            imprimirNaGrid(objeto.lerCsv());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarMatriculaActionPerformed

    private void jButtonOrdenarDepartamentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarDepartamentoNomeActionPerformed
        try {
            OrdenarDepartamentoNome objeto = new OrdenarDepartamentoNome();
            imprimirNaGrid(objeto.lerCsv());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarDepartamentoNomeActionPerformed

    private void jButtonOrdenarContratoTitulacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarContratoTitulacaoNomeActionPerformed
        try {
            OrdenarContratoTitulacaoNome objeto = new OrdenarContratoTitulacaoNome();
            imprimirNaGrid(objeto.lerCsv());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonOrdenarContratoTitulacaoNomeActionPerformed

    private void jButtonOrdenarContratoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarContratoNomeActionPerformed
        try {
            OrdenarContratoNome objeto = new OrdenarContratoNome();
            imprimirNaGrid(objeto.lerCsv());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarContratoNomeActionPerformed

    private void jButtonOrdenarTitulacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarTitulacaoNomeActionPerformed
        try {
            OrdenarTitulacaoNome objeto = new OrdenarTitulacaoNome();
            imprimirNaGrid(objeto.lerCsv());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarTitulacaoNomeActionPerformed

    private void jButtonOrdenarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNomeActionPerformed
        try {
            OrdenarNome objeto = new OrdenarNome();
            imprimirNaGrid(objeto.lerCsv());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarNomeActionPerformed

    private void jButtonOrdenarDepartamentoTitulacaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarDepartamentoTitulacaoNomeActionPerformed
        try {
            OrdenarDepartamentoTitulacaoNome objeto = new OrdenarDepartamentoTitulacaoNome();
            imprimirNaGrid(objeto.lerCsv());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButtonOrdenarDepartamentoTitulacaoNomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //limpa a Tabela
        ((DefaultTableModel) jTable1Tabela.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOrdenarContratoNome;
    private javax.swing.JButton jButtonOrdenarContratoTitulacaoNome;
    private javax.swing.JButton jButtonOrdenarDepartamentoNome;
    private javax.swing.JButton jButtonOrdenarDepartamentoTitulacaoNome;
    private javax.swing.JButton jButtonOrdenarMatricula;
    private javax.swing.JButton jButtonOrdenarNome;
    private javax.swing.JButton jButtonOrdenarPorNome6;
    private javax.swing.JButton jButtonOrdenarTitulacaoNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Tabela;
    // End of variables declaration//GEN-END:variables
}
